/**
 * FIFO PRO — version.js
 * The RUNNING bundle's version stamp. AUTO-GENERATED by
 * tools/bump-version.sh — do not edit by hand; edit via the bump script
 * so version.json / sw.js / this file can never drift apart.
 *
 * window.APP_BUILD is compared by js/versionGuard.js against the LIVE
 * version.json (fetched with cache:'no-store') to detect that a newer
 * release was deployed while this bundle is still loaded.
 */
window.APP_BUILD = {
  version: "2.2.0",
  build: "2026-07-23.7",
  cache: "fifopro-v2.2.0-2026-07-23.7"
};
