#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# FIFO PRO — tools/bump-version.sh
# The ONE command that stamps a release version everywhere at once,
# so version.json / js/version.js / sw.js can never drift apart.
#
# Usage:
#   ./tools/bump-version.sh 2.0.1            # required update (default)
#   ./tools/bump-version.sh 2.0.1 optional   # non-blocking update
#
# What it writes (single source of truth = your argument):
#   version.json   {version, build, required, cache}
#   js/version.js  window.APP_BUILD {version, build, cache}
#   sw.js          const BUILD_CACHE = '<cache>'
#
# Build id = <version>-<YYYY-MM-DD>.<n> where n auto-increments if you
# release the same version twice on the same day.
# ═══════════════════════════════════════════════════════════════
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION="${1:?usage: bump-version.sh <semver> [optional]}"
REQUIRED="true"
[ "${2:-required}" = "optional" ] && REQUIRED="false"

DATE=$(date +%F)
N=1
if [ -f version.json ]; then
  PREV=$(grep -o '"build": *"[^"]*"' version.json | cut -d'"' -f4)
  case "$PREV" in
    "$DATE".*) N=$(( ${PREV##*.} + 1 )) ;;
  esac
fi
BUILD="$DATE.$N"
CACHE="fifopro-v$VERSION-$BUILD"

cat > version.json <<EOF
{
  "version": "$VERSION",
  "build": "$BUILD",
  "required": $REQUIRED,
  "cache": "$CACHE"
}
EOF

cat > js/version.js <<EOF
/**
 * FIFO PRO — version.js
 * The RUNNING bundle's version stamp. AUTO-GENERATED by
 * tools/bump-version.sh — do not edit by hand; edit via the bump script
 * so version.json / sw.js / this file can never drift apart.
 *
 * window.APP_BUILD is compared by js/versionGuard.js against the LIVE
 * version.json (fetched with cache:'no-store') to detect that a newer
 * release was deployed while this bundle is still loaded.
 */
window.APP_BUILD = {
  version: "$VERSION",
  build: "$BUILD",
  cache: "$CACHE"
};
EOF

# Stamp the SW cache constant (single line, marker-based)
if grep -q "^const BUILD_CACHE" sw.js; then
  sed -i '' "s|^const BUILD_CACHE = .*|const BUILD_CACHE = '$CACHE';|" sw.js
else
  echo "ERROR: sw.js is missing the 'const BUILD_CACHE' marker line" >&2
  exit 1
fi

echo "Stamped $VERSION ($BUILD, required=$REQUIRED)"
echo "  version.json  ✓"
echo "  js/version.js ✓"
echo "  sw.js         ✓  (BUILD_CACHE=$CACHE)"
echo
echo "Release checklist: commit → push → cache-busted check of live"
echo "version.json → open the live site and confirm the update overlay"
echo "appears on an old session."
